import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const storageSource=fs.readFileSync(new URL('../public/read-storage.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const options={sourceSetDigest:'edition-a',noteStorageAnchor:'zphlm-test'};
function setup(storage){const ctx={window:{localStorage:storage},Map,Date};vm.runInNewContext(storageSource,ctx);return ctx.window.ZPHLMStorage.create;}
function memory(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
test('private notes survive a fresh store and export/import preserves anchored text',()=>{const s=memory(),create=setup(s),a=create(options);a.saveNote('c01-001','閱讀驗證筆記');assert.equal(create(options).getNote('c01-001').text,'閱讀驗證筆記');const other=setup(memory())(options);assert.equal(other.importNotes(a.exportNotes()).imported,1);assert.equal(other.getNote('c01-001').text,'閱讀驗證筆記');assert.throws(()=>other.importNotes({...a.exportNotes(),sourceSetDigest:'wrong-edition'}));assert.equal(other.getNote('c01-001').text,'閱讀驗證筆記');});
test('blocked browser storage retains notes in-session and reports persistence truthfully',()=>{const bad={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')},removeItem(){throw Error('blocked')}};const s=setup(bad)(options);s.saveNote('c01-001','session note');assert.equal(s.isPersistent(),false);assert.equal(s.getNote('c01-001').text,'session note');assert.equal(s.exportNotes().notes.length,1);});
test('bottom navigation preserves reading scroll and active tab is a no-op',()=>{const els=new Map();function el(id){if(!els.has(id))els.set(id,{hidden:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},removeAttribute(){}});return els.get(id)}const ctx={state:{view:'read'},viewScroll:{read:0,rankings:0,about:0},window:{scrollY:720,scrollTo(o){this.scrollY=o.top}},document:{getElementById:el,querySelector:el},loadRankings(){},renderAbout(){}};vm.runInNewContext(app.slice(app.indexOf('  function switchView('),app.indexOf('  function renderChapter(')),ctx);ctx.switchView('read');assert.equal(ctx.window.scrollY,720);ctx.switchView('about');assert.equal(ctx.window.scrollY,0);ctx.switchView('read');assert.equal(ctx.window.scrollY,720);});
test('out-of-order chapter requests never replace the latest selected chapter',async()=>{const pending={},rendered=[];const ctx={chapterRequest:0,CH:[{id:'a'},{id:'b'}],chapterIndex:id=>id==='a'?0:1,state:{view:'read'},displayedChapter:null,viewScroll:{read:0},document:{getElementById:()=>({innerHTML:''})},esc:String,t:()=>'',fetchChapter:id=>new Promise(resolve=>pending[id]=resolve),renderChapter:c=>rendered.push(c.id),window:{scrollTo(){}},scrollToAnchor(){}};vm.runInNewContext(app.slice(app.indexOf('  function loadAndDisplay('),app.indexOf('  function scrollToAnchor(')),ctx);ctx.loadAndDisplay('a');ctx.loadAndDisplay('b');pending.b([]);await Promise.resolve();pending.a([]);await Promise.resolve();assert.deepEqual(rendered,['b']);});
